defaults:
  - trainer: default
  - data: ada
  - model: default
  - optim: default
  - logger: default
  - callbacks/checkpoint: default
  - callbacks/early_stopping: default
  - _self_

hydra:
  run:
    dir: .

trainer:
  gpus: 1
  profiler: null
  progress_bar_refresh_rate: 10
  benchmark: true

data:
  batch_size: 32
  num_workers: 1
  random_sampler: false
